server:
  port: 8090

spring:
  application:
    name: mock-websocket

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.example.mockwebsocket: DEBUG
    org.springframework.web.socket: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mock:
  kis:
    stocks:
      - code: "005930"
        name: "삼성전자"
      - code: "000660"
        name: "SK하이닉스"
      - code: "035420"
        name: "NAVER"
      - code: "035720"
        name: "카카오"
    update-interval: 1000
