name: 기능 구현 계획
about: 새로운 기능 구현 목표와 계획을 작성합니다.
title: "[PLAN] "
labels: plan
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## 새로운 기능 구현을 위한 계획을 세워봅시다!
        아래 양식에 맞춰 기능의 목적과 계획을 상세하게 작성해주세요.

  - type: textarea
    id: purpose
    attributes:
      label: 구현 목적
      description: 이 기능이 해결하려는 문제 또는 달성하고자 하는 목표는 무엇인가요?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 구현하려는 기능에 대해 최대한 상세하게 설명해주세요. (예시: UI/UX, API 명세)
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: 할 일 (Task List)
      description: 기능을 구현하기 위해 필요한 작업들을 체크리스트로 관리하세요.
      options:
        - label: API 설계 및 구현
        - label: 데이터베이스 스키마 설계
        - label: 프론트엔드 UI/UX 구현
        - label: 테스트 코드 작성
        - label: 배포 및 문서 업데이트

  - type: input
    id: deadline
    attributes:
      label: 마감일
      description: 예상되는 마감일이 있다면 작성해주세요.
      placeholder: YYYY-MM-DD

  - type: textarea
    id: reference
    attributes:
      label: 참고 자료
      description: 기능 구현에 필요한 참고 자료나 링크를 기록해두세요.
